# Return a list of all xrefs for non-obsolete classes
# NOTE: language tags are removed from labels & xrefs

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?id ?label ?xref
WHERE {
    ?class a owl:Class ;
        oboInOwl:hasDbXref ?xref ;
        oboInOwl:id ?id ;
        rdfs:label ?label .

    FILTER(CONTAINS(STR(?class), "DOID"))
    FILTER NOT EXISTS { ?class owl:deprecated ?obsolete . }
}
ORDER BY ?label ?xref
