PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT 
	(COUNT(?ia) AS ?infectiousAgent)
WHERE {
	?ia rdfs:subClassOf* obo:DOID_0050117 .
}