prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix DOID: <http://purl.obolibrary.org/obo/DOID_>

SELECT ?extClass ?label WHERE 
{
  ?extClass a owl:Class ;
            rdfs:label ?label
  FILTER( regex(STR(?extClass), "OMIM"))
  FILTER( NOT EXISTS {?extClass owl:equivalentClass ?equivalentClass } )
  FILTER( NOT EXISTS {?extClass rdfs:subClassOf ?sc . FILTER( ?sc != DOID:630) } )
  FILTER( NOT EXISTS {?sc rdfs:subClassOf ?extClass . FILTER( regex(STR(?sc), "DOID")) } )

}
