# Ensure that there are no subclass cycles, and the structure is a tree

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?s WHERE {
	?s a owl:Class .
	?s rdfs:subClassOf+ ?p .
	?p rdfs:subClassOf+ ?s .
	FILTER (!isBlank(?s))
}