prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?baseClass ?baseLabel ?equivalentClass ?equivalentLabel WHERE 
{
  ?baseClass owl:equivalentClass ?equivalentClass .
  ?baseClass rdfs:label ?baseLabel .
  ?equivalentClass rdfs:label ?equivalentLabel .

  FILTER (!isBlank(?baseClass)) .
  FILTER (!isBlank(?equivalentClass))

}
