prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix DOID: <http://purl.obolibrary.org/obo/DOID_>

SELECT ?baseClass ?baseLabel ?superClass ?superLabel WHERE 
{
  ?baseClass rdfs:subClassOf ?superClass .
  ?baseClass rdfs:label ?baseLabel .
  ?superClass rdfs:label ?superLabel .

  FILTER (!isBlank(?baseClass)) 
  FILTER (!isBlank(?superClass))

   BIND(REPLACE(str(?baseClass), '_.*$', "") AS ?basePrefix)
   BIND(REPLACE(str(?superClass), '_.*$', "") AS ?superPrefix)

  FILTER(?basePrefix != ?superPrefix)

  FILTER(?superClass != DOID:630)

}
