# Get xrefs for a range of DOIDs (using IDs as numbers)
# Example: All ICD9, ICD10, & SNOMED xrefs for DOIDs from 0 to 199
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX DOID: <http://purl.obolibrary.org/obo/DOID_>

SELECT ?id ?label ?xref
WHERE {
	?class oboInOwl:id ?id ;
		rdfs:label ?label ;
		oboInOwl:hasDbXref ?xref .
	FILTER( REGEX(?xref, "^(ICD9|ICD10|SNOMED)") )
	FILTER NOT EXISTS { ?class owl:deprecated true }

	BIND( xsd:integer( STRAFTER( ?id, "DOID:" ) ) AS ?id_n )
	FILTER( ?id_n >= 100 && ?id_n < 200 )
}
