# Returns entities with text that have an English language tag (includes
# deprecated entities and regional variants to ensure file-wide consistency)

SELECT DISTINCT ?entity ?property ?value
WHERE {
	?entity ?property ?value .
	FILTER(langMatches(lang(?value), "en"))
}