# identifies invalid predicates used for ECO codes

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?entity ?property ?value
WHERE {
	?entity a owl:Class ;
		obo:IAO_0000115 ?definition .
	?blank owl:annotatedTarget ?definition ;
		?property ?value .
	FILTER(CONTAINS(STR(?value), "ECO_"))
	FILTER NOT EXISTS { ?blank dc:type ?value . }
	FILTER NOT EXISTS { ?entity owl:deprecated "true"^^xsd:boolean }
}
