# identifies definition xrefs (URLs) annotated on the class instead of
# directly annotated on the definition

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?entity ?property ?value
WHERE {
	VALUES ?property { oboInOwl:hasDbXref }
	?entity a owl:Class ;
		?property ?value .

	FILTER(REGEX(?value, "https?:"))
	FILTER NOT EXISTS { ?entity owl:deprecated "true"^^xsd:boolean }
}
