# Ensure that all entities in the disease_ontology namespace have the correct IRI

PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?invalid_iri
WHERE {
	?invalid_iri a owl:Class ;
	   oboInOwl:hasOBONamespace "disease_ontology" .
	FILTER(!REGEX(STR(?invalid_iri), "^http://purl\\.obolibrary\\.org/obo/DOID_[0-9]{1,7}$"))
}
