# verify all 'has symptom' axioms use SYMP
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?not_disease
WHERE {
    ?anonymous a owl:Restriction ;
        owl:onProperty obo:RO_0004029 ;
        owl:someValuesFrom ?not_disease .

    FILTER(isBlank(?anonymous))
    FILTER(!isBlank(?not_disease) && !CONTAINS(str(?not_disease), "DOID"))
}