# Ensure that no class is orphaned (excluding top level 'disease')

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?s
WHERE {
	?s a owl:Class .
	FILTER NOT EXISTS { ?s rdfs:subClassOf ?p }
	FILTER NOT EXISTS { ?s owl:deprecated "true"^^xsd:boolean }
	FILTER (!STRENDS(str(?s), "DOID_4"))
}