# return NCI xrefs that are used on more than one DO class

PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?xref ?id ?id2 ?label ?label2 WHERE {
	?s oboInOwl:id ?id ;
	   rdfs:label ?label ;
	   oboInOwl:hasDbXref ?xref .
	?s2 oboInOwl:id ?id2 ;
		rdfs:label ?label2 ;
		oboInOwl:hasDbXref ?xref .
	FILTER(?s != ?s2)
	FILTER(STRSTARTS(STR(?xref), "NCI:"))
}
ORDER BY ?xref
