name: Update Releases
on:
  release:
    types: [published]
jobs:
  resources:
    name: Update Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install GH CLI
        run: brew install gh
      - name: Login to GH
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "$TOKEN" > .token.txt && gh auth login --with-token < .token.txt && rm .token.txt
      - name: Update Releases
        run: python3 src/util/update-releases.py RELEASES.md
      - name: Commit Changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: RELEASES.md
          commit-msg: Update RELEASES.md
          github-token: ${{ secrets.GH_TOKEN }}